version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.4
    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install .[test]
      - run:
          name: 'Pylinting'
          command: |
            . venv/bin/activate
            pip install .[test]
            pylint tap_kafka -d C,W,unexpected-keyword-arg,duplicate-code
      - run:
          name: 'Unit Tests'
          command: |
            . venv/bin/activate
            pytest tests/

workflows:
  version: 2
  build:
    jobs:
      - build