"""Default configuration values"""
import os

DEFAULT_INITIAL_START_TIME = 'latest'
DEFAULT_PARTITIONS = []
DEFAULT_BOOKMARK_PRECEDENCE = ['offset', 'timestamp', 'start_time']
DEFAULT_MAX_RUNTIME_MS = 300000
DEFAULT_COMMIT_INTERVAL_MS = 5000
DEFAULT_CONSUMER_TIMEOUT_MS = 10000
DEFAULT_SESSION_TIMEOUT_MS = 30000
DEFAULT_HEARTBEAT_INTERVAL_MS = 10000
DEFAULT_MAX_POLL_INTERVAL_MS = 300000
DEFAULT_MAX_POLL_RECORDS = 500
DEFAULT_MESSAGE_FORMAT = 'json'
DEFAULT_PROTO_SCHEMA = None
DEFAULT_PROTO_CLASSES_DIR = os.path.join(os.getcwd(), 'tap-kafka-proto-classes')
DEFAULT_SECURITY_PROTOCOL = 'SASL_SSL'
DEFAULT_SASL_MECHANISMS = 'PLAIN'